model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: 'train/epoch_num'
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 64
      in_channels: 3
      out_ch: 3
      ch: 32
      ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1 64, 32, 16, 8
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    wrap: True
    train:
      target: ldm.data.dis.MPI3DTrain

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        log_images_kwargs:
          inpaint: False
  trainer:
    benchmark: True
    accumulate_grad_batches: 2
