model:
  base_learning_rate: 2.0e-6   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 16
    channels: 4
    cond_stage_trainable: false ##################
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 16
        in_channels: 4
        out_channels: 4
        model_channels: 64
        attention_resolutions: [ 1, 2, 4]   # 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ]  # 8,4,2,1
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "/my/checkpoint/path"
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 64
          in_channels: 3
          out_ch: 3
          ch: 32
          ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1 64, 32, 16, 8
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    wrap: True
    num_workers: 8
    train:
      target: ldm.data.dis.MPI3DTrain
      # params:
      #   size: 64
      # degradation: pil_nearest
    # validation:
    #   target: ldm.data.dis.MPI3DTrain
      # params:
      #   size: 64
      # degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: false
        log_images_kwargs:
          inpaint: false
  trainer:
    benchmark: True